---
- name: Ensure epel-release is installed
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install graphite-api package dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ graphite_api_package_dependencies }}"

- name: Install graphite-api via pip
  ansible.builtin.pip:
    name: "{{graphite_api_pip_package }}"
    state: present
  when: graphite_api_manage_webserver | bool

- name: Place graphite-api.yaml configuration
  ansible.builtin.template:
    src: graphite-api.yaml.j2
    dest: /etc/graphite-api.yaml
    mode: '0644'
    owner: root
    group: root

- name: Ensure storage-dir exists
  ansible.builtin.file:
    path: "{{ graphite_api_storage_dir }}"
    state: directory
    mode: '0750'
    owner: "{{ graphite_api_webserver_user }}"
