---
- name: Fetch package from source
  ansible.builtin.get_url:
    url: "{{ go_carbon_release_package }}"
    dest: /tmp
    mode: '0755'
  register: _fetched_source
  changed_when: false

- name: Apt - Install go-carbon
  ansible.builtin.apt:
    deb: "{{ _fetched_source.dest }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Dnf - Install go-carbon
  ansible.builtin.dnf:
    name: "{{ _fetched_source.dest }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure storage-dir exists
  ansible.builtin.file:
    path: "{{ go_carbon_storage_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ go_carbon_user }}"
    group: "{{ go_carbon_group }}"

- name: Place go-carbon configuration
  ansible.builtin.template:
    src: go-carbon.conf.j2
    dest: /etc/go-carbon/go-carbon.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart go-carbon

- name: Place storage-schemas configuration
  ansible.builtin.template:
    src: storage-schemas.conf.j2
    dest: /etc/go-carbon/storage-schemas.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart go-carbon

- name: Place storage-aggregation configuration
  ansible.builtin.template:
    src: storage-aggregation.conf.j2
    dest: /etc/go-carbon/storage-aggregation.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart go-carbon
