namespace: tbauriedel
name: gographite
version: 0.0.1
readme: README.md
authors:
  - Tobias Bauriedel <tobias@bauriedel.de>
description: >
  Installs / configure go-carbon and carbonapi.
license:
  - Apache-2.0
tags:
  - collection
  - metrics
  - graphite
  - go-carbon
dependencies: {}
repository: https://github.com/tbauriedel/ansible-collection-gographite
