namespace: tbauriedel
name: gographite
version: 0.0.3
readme: README.md
authors:
  - Tobias Bauriedel <tobias@bauriedel.de>
description: >
  Ansible collection for the installation and configuration of the tool stack around the go-graphite project.
license:
  - Apache-2.0
tags:
  - collection
  - metrics
  - gographite
  - gocarbon
  - carbonapi
dependencies: {}
repository: https://github.com/tbauriedel/ansible-collection-gographite
