# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.hostname = "graphite-ubuntu"
        ubuntu.vm.box = "bento/ubuntu-20.04"
        ubuntu.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = "vv"
        end
    end
end