---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: libcairo2-dev
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"
